### PR TITLE
feat: anti zip

### PR DESCRIPTION
**Pull request by rushiiMachine**
- Nuke zips from non-ignored roles (prevent malicious plugins) 
- Share ignored roles between anti-zip & auto replies

### CODE REVIEW

**Comment by Juby210** [comment]
Maybe do that in support channels only

**Comment by rushiiMachine** [comment]
Why though
Theres no reason for other users to be sending zips anyways

**Comment by Vendicated** [comment]
there are many cases where you'd want to send a zip lol and it's not like zip themselves are dangerous

**Comment by Vendicated** [comment]
Also if we're doing this already, why not ban other dangerous files like exe or jar too?

**Comment by ghost** [comment]
I'd just start using Tar, Rar, Zstd, or 7zip achieves if zips got banned lol.

E.g. archive the zip archives with a different archive format.

**Comment by rushiiMachine** [comment]
ready for review, added target channels opt

**Pull request closed without merging**
